name: walletconnect_dart
description: Open protocol for connecting decentralised applications to mobile wallets with QR code scanning or deep linking.
version: 0.0.11
homepage: https://walletconnect.org/
repository: https://github.com/RootSoft/walletconnect-dart-sdk
issue_tracker: https://github.com/RootSoft/walletconnect-dart-sdk/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  # WebSocket Channel
  web_socket_channel: ^3.0.0

  # UUID
  uuid: '>=3.0.0 <5.0.0'

  # Cryptography
  cryptography: ^2.0.5

  # Hex
  convert: ^3.1.0

  # JSON Annotation
  json_annotation: ^4.7.0

  # Stack trace
  stack_trace: ^1.10.0

  cbor: 4.1.0

dev_dependencies:
  # Testing framework
  test: ^1.21.4

  # JSON Serialization
  json_serializable: ^6.5.4

  # Build runner
  build_runner: ^2.3.0
